name: Update description in Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md

concurrency: build-images

jobs:
  update-description:
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
      - uses: actions/checkout@v6

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: brightcodecompany/openintegrationengine
